<?php
function bakery_user_menu() {
    $items = array();
    $items['welcome'] = array(
        'title' => 'Hi There!',
        'page callback' => 'welcome_new_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function welcome_new_user() {
    return '<p>Welcome!</p>';
}

function bakery_user_user_login($edit, $account, $category) {
    $_GET['destination'] = 'welcome';
}
